### ISSUE TITLE
Issue: RuntimeError: Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by jds250** [yandex-research/specexec#1]
Hi, this is a great work! I am trying to test the offload setup, When running the following command:
`python run_exp.py --top_p 0.9 --temperature 0.6 --gen_type SpecExecBase --max_budget="16, 32, 64, 128, 256, 512, 1024" --n_tests=10 --offload --exp_name="SX_sample_offload"
`
I met `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_bmm)
`
It seems like `freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)` there happened CPU tensor @ GPU tensor, as I debugged, inv_freq is a cpu tensor , I wonder why this happened ? 

Can u help me? Thanks!

**Comment by chuncheyang1130** [comment]
Hi, I also meet the same problem while running the same command

**Comment by chuncheyang1130** [comment]
I found out that ```model.rotary_emb``` is not set to ```cuda:0```in the device map in ```load_offloaded_model``` function, adding this setup would fix the problem

**Comment by poedator** [comment]
@jds250 - sorry for leaving your issue without attention for so long. There was in deed a bug in code. Fixed it today.
@chuncheyang1130 - Thank you for pinpointing the solution!
