### ISSUE TITLE
SpecExec works slowly

### ISSUE THREAD

**Issue by deafTim** [yandex-research/specexec#2]
Tested SpecExec on CPU on 2 models: TinyLlama_v1.1, llama-68m and got the following result:

```
Namespace(exp_name='TinyLlama', save_dir='logs', model_0='TinyLlama_v1.1', model_1='Llama-68m', dataset='oasst', dataset_start_index=0, gen_type='SpecExecBase', temperature=0.0, top_p=0.9, temp=None, n_tests=1, max_n_beams='128', max_beam_len='32', branching=None, max_budget='16,32,64,128,256,512', max_branch_width='32', tree_max_len=4096, replacement=False, repack=False, max_new_tokens=1024, min_log_prob=None, verbose=False, loglevel='WARNING', debug=False, seed=0, offload=False, device_size=1, wandb=False, draft_temperature=None, wandb_project='spec_trees', zero=False, draft_engine_class='EngineRegular')
```
       S U M M A R Y   R E S U L T S   TinyLlama 
```
   beams  max_h  budget minLP  branch       t0       t1  tree_h  tree_size  min_CLP  exp_time  gen_rate  gen_speed
0    128     32      16  None      32   3.6913   0.8427    15.5       16.0    -3.11    309.70     16.30       3.60
1    128     32      32  None      32   6.8735   1.5826    29.6       32.0    -3.69    299.22     30.26       3.58
2    128     32      64  None      32   6.7021   3.0498    27.2       64.0    -5.18    432.24     24.02       2.46
3    128     32     128  None      32   9.3451   5.7605    30.1      128.0    -6.20    605.63     27.00       1.79
4    128     32     256  None      32  13.4624  11.1349    29.4      256.0    -6.58   1033.29     25.10       1.02
5    128     32     512  None      32  22.9044  21.7741    30.9      512.0    -7.47   1784.97     26.82       0.60
```
When testing TinyLlama_v1.1 separately with Transformers, it works with speed 5.5 tokens/sec.
Maximal speed of SpecExec is 3.6 tokens/sec.
My question: is it OK or my understanding of input parameters is wrong?

**Comment by poedator** [comment]
HI, @deafTim 
thank you for testing the limits of this method.
Not every combination of two models will be accelerated by SpecExec. Best use case is very large target model (up to 70B, tinyllama_1B is too small) + reasonably capable draft model (1-3-7B), ideally with offloading baseline, so that there is relative time budget for the drafting.

**Comment by deafTim** [comment]
Hi, @poedator,
Thank you for answer. I think, you are right. Models do not fit to each other well.
What is additionally strange here, if I use models in right order: model_0=Llama-68m, model_1=TinyLlama_v1.1, the gen_speed became much smaller.
